src/resources/fr-FR.js
I corrected syntax errors, spelling mistakes and typos in French validation messages.
=> Corrected French validation messages

src/resources/nl-NL.js
=> small typo

doc/Intro.md, src/resources/es-MX.js
Translation file for es-MX language
=> feat(i18n): added es-MX language resource

src/validation/validate-custom-attribute.js
=> fix(validate-custom-attribute): remove import

doc/Intro.md
Some typos in aurelia-app -> aurelia-main="main", should be aurelia-app="main"
=> Fixed typos

doc/Intro.md, src/resources/bg-BG.js, test/i18n.spec.js
Add resource file for Bulgarian language
=> feat(i18n): add resource for language bg-BG

config.js
Fixes #63 caused by not running jspm clean after updating dependencies.
=> fix(jspm): Fixes config.js fork issue

config.js, package.json
Fixes issues with templating forks
=> chore(update): Update to latest releases

src/resources/da-DK.js
Adds Danish language to validation messages
=> Locale da-DK

src/index.js, src/resources/nb-NO.js, src/resources/nn-NO.js
Not sure if you are supposed to run the gulp tasks to generate new dist files when making a PR, so chose not to to be on the safe side.
=> Fix make plugin global after API change and added Norwegian language files

src/validation/validation-rules.js
Fixes https://github.com/aurelia/validation/issues/92
Feel free to close this PR if there is a better solution.
=> fix(validation-rules): fixes translation errors in minified bundle

src/validation/debouncer.js
=> Remove unneeded (circular) dependency.

src/resources/ca-ES.js
Catalan language, ca-ES, added. Volem votar
=> Catalan language, ca-ES, added

build/tasks/doc.js, doc/core-js.d.ts, package.json
generates [this](https://gist.github.com/JeroenVinke/c0e24a871ceee02ca3f4) in doc/api.json
=> feat(doc-generation): generate api.json

src/resources/pt-BR.js
=> feat(I18N): add pt-BR

package.json
=> chore(package): add build resources

doc/article/en-US/validation-basics.md
=> doc(basics): add validator documentation

doc/article/en-US/validation-basics.md
The message has `\${config.max}` this should be `\${$config.max}`.
=> Custom Rules integerRange missing $ for message

src/implementation/validation-parser.ts, test/validation-parser.ts
https://github.com/aurelia/validation/issues/324
=> Fixed aurelia/validation/issues/324

doc/article/en-US/validation-basics.md
Fixed small type of extra bracket that wasn't needed.
=> Fixed small typo

doc/article/en-US/validation-basics.md
Fix the outlining of the fields in the translation files example code.
=> doc(translation-files) fix outlining

doc/article/en-US/validation-basics.md
Small correction in documentation
=> blurOrChange corrected into changeOrBlur

doc/article/en-US/validation-basics.md
Based on a use case I worked out for myself, which I imagine people might find interesting. It illustrates some advanced techniques for controlling validation on a fine-grained level.
For a working example of the template and view model see https://gist.run/?id=c533e53e62cb348cc96aa9445bae612a
=> doc(basics): add section 'Multiple validation controllers'

doc/article/en-US/validation-basics.md, src/implementation/validation-rules.ts
=> feat(ValidationRules): add method untaggedRules()

src/validation-controller.ts
I'm not a 100% sure it works in every scenarios, but it works for my (simple enough) use cases.
fixes #456
=> fix(validation-controller): fix revalidateErrors method

src/validation-errors-custom-attribute.ts
Fixes same problem as this one in i18n: https://github.com/aurelia/i18n/pull/266/commits/7c2a2d09fa0966327250af63aa97093975dcec1d
=> fix(DI): use static method for Element 

src/validation-renderer-custom-attribute.ts
=> fix(CustomAttribute): import customAttribute from aurelia-templating

package-lock.json, package.json, rollup.config.js, tsconfig.json
Adjust dts generation so that site generator can work with it.
@jdanyow @EisenbergEffect
=> refactor(build -- dts): merge all dts into 1 file

package.json
=> chore(build): fix build path
