aurelia/validation

src/validation/path-observer.js, src/validation/validation-group.js, src/validation/validation-property.js
I've improved the `destroy()` function on `ValidationGroup`.
Now calling `destroy()` will clean up the subscription of the `PathObserver` for each `ValidationResultProperty` (now `PathObserver` has an `unsubscribe()` method).
I was having issues with a form with a dynamic array of values, recreating the validation group was creating new observers each time and some fields ended up triggering multiple validations (also on other fields of the form when adding and removing element of an array).
Calling `destroy()` on the `ValidationGroup` and recreating it solves the issue with this patch, since all observables get unsubscribed correctly.
=> fix(validation-group): clean up of path observer subscriptions on validation group destroy

src/validation/decorators.js, src/validation/validation-group.js
Cleaner / more compliant with the way it is done in Aurelia.
Fixes #64.
**NOTE**: This creates a direct dependency on `aurelia-metadata`, whose build configuration is _not_ included in this PR.
=> Uses `aurelia-metadata` for metadata handling

src/validation/path-observer.js
I experienced, yet again (https://github.com/aurelia/validation/pull/65), major headaches with the path observer subscribe/unsubscribe mechanics.
I tracked down the issue in the end, it seems like the callbacks of a path observer need to be cleaned up when unsubscribing, otherwise on subscribe it can happen that a path observer fires change callbacks on the wrong field (it happens when I use dynamic forms validation as I reported in details [here](https://github.com/aurelia/validation/issues/10#issuecomment-116308175))
I'm not really sure what the following block of code does: https://github.com/aurelia/validation/blob/master/src/validation/path-observer.js#L61-L67
Removing the block of code completely does not cause any issue to my application, but I opted for a simpler PR to overcome …
=> fix(path-observer): clean up of callbacks when unsubscribing from a path observer

config.js, package.json, test/setup.js
There were two missing parts to the latest PR to update
dependencies in aurelia-validation:
* aurelia-metadata must be brought in as a dependency
* there was an error with the test reference to resources
=> fix(tests): update dependencies to ensure tests run again

build/tasks/build.js
allows for subdirectories without messing up the typescript definitions
=> feat(dts-generation): support subdirectories

src/validation-rules.js, test/validationRules/between-length.spec.js, test/validationRules/maximum-length.spec.js, test/validationRules/minum-length.spec.js
Validating the length of numbers was broken in a few places, as noted in #136, here are some fixes.
Basically the bug happens because length is measured and compared using `.length`, which is not a method on `Number`, so I'm checking the `typeof` on values passed into `BetweenLengthValidationRule`, `MaximumLengthValidationRule` and `MinimumLengthValidationRule`. If it's a `Number`, convert it to a `String`.
Simples.
This is my first PR, so if I've done something per convention please let me know.
:heart:
=> Fix validating length of numbers

src/decorators.js, src/validation-group-builder.js, src/validation-group.js, src/validation-result.js, src/validation-rules.js, src/validation.js
Please merge this pull request and run `gulp build` to update dist folder.
This pull request improves generated TypeScript declarations (see #170).
This pull request includes initial work from @stephenlautier (see commit https://github.com/stephenlautier/validation/commit/1ea917b55dc3374b72c233d6bf251520f61c9c9a and https://github.com/stephenlautier/validation/commit/7a5eb63b4d95dd1c7e0044ed0421ce432cc120a2) and my fixes/improvements mentioned in his pull request https://github.com/aurelia/validation/pull/162/files as well other my own improvements on that matter for other methods.
=> For issue #170 type script improvements

src/validation-group.js
#216 Fixed issue where the core-js polyfills for metadata use the object definition of an object to store the metadata. The polyfills store the metadata in a weakmap, which means that it cannot be looked up by using an instance of an object.
=> Fix ensure decorators not working with latest core-js

config.js, package.json, src/validation-locale.js
Fixes #226 when the loader was previously using System.js to load
instead of the app-wide loader.  Temporarily uses the global container
to get the app loader and use that instead to load the module.
=> fix(loader): switch to using apps loader

package.json
This PR fixes [this issue](https://github.com/aurelia/webpack-plugin/issues/48) on `aurelia-webpack-plugin` where resources aren't declared in the `package.json` and thus not available at build time.
=> Add proper resources to package.json for webpack

package.json
test and build works
*unrelated': build:doc fails with `TypeError: Cannot read property 'flags' of undefined`. maybe someone else can chip in
closes https://github.com/aurelia/validation/issues/337
=> feat(scripts): use cross-env and rifraf for cross environment scripts

src/validation-controller-factory.ts, src/validation-controller.ts, test/validation-controller-factory.ts
feat(ValidationControllerFactory): add Validator parameter to createForCurrentScope
It is not currently possible to provide a Validater to a specific
instance of ValidationController, at least, not without using injection.
ValidationControllerFactory.createForCurrentScope has been provided to enable
us to instantiate ValidationController without the use of injection, but
provides no means of supplying a Validator for the controller instance.
I have a use case where the ValidationController needs to be
instantiated without the use of injection because the code is in a base
class where, due to javascript/typescript limitations, injection cannot
be used.
Note: I'm not altering the documentation because it ties into:
1) documentation about configuring the plugin, which I believe is
missing …
=> feat(ValidationControllerFactory): add Validator parameter to createForCurrentScope

doc/article/en-US/validation-basics.md
I believe `.then()` is missing in the second sequencing example in order to make `usernameNotInUse` be evaluated after the first 3 pass.
Also adds a missing semicolon.
=> doc(basic): add missing then()

doc/article/en-US/validation-basics.md
The "Setting the validate trigger" example used an incorrect `inject` attribute (one closing parenthesis too many).
=> Fix incorrect @inject sample

doc/article/en-US/validation-basics.md
The docs use "targetting" instead of the more commonplace "targeting".
=> Fixed typos

doc/article/en-US/validation-basics.md
Edits:
Under "Displaying Errors" section:
"The validation-errors custom attribute implements the ValidationRenderer interface."
"It also automatically adds itself to the controller using addRenderer when its "bind" lifecycle..."
=> Fixes to Documentation typos in Update validation-basics.md

src/validation-errors-custom-attribute.ts, test/resources/index.ts, test/resources/validation-errors-form-one.ts, test/validation-errors-custom-attribute.ts
This is a fix for #391.
It depends on two other PRs:
https://github.com/aurelia/templating/pull/515
https://github.com/aurelia/templating-binding/pull/110
=> validation-errors attribute doesn't work with not-in-scope validation controller #391

src/implementation/validation-parser.ts, test/validation-parser.ts
This enables the code to parse the function below.
'  ------------------------------------------------
Inner Error:
Message: Unable to parse accessor function:
function (field){__cov_Y78wk1Q$EdTFqyA$ttpw0g.f['7']++;__cov_Y78wk1Q$EdTFqyA$ttpw0g.s['17']++;return field.number;}
Inner Error Stack:
Error: Unable to parse accessor function:
function (field){__cov_Y78wk1Q$EdTFqyA$ttpw0g.f['7']++;__cov_Y78wk1Q$EdTFqyA$ttpw0g.s['17']++;return field.number;}
at ValidationParser.getAccessorExpression (http://localhost:9876/base/jspm_packages/npm/aurelia-validation@1.0.0-beta.1.0.1/implementation/validation-parser.js:57:23)
at ValidationParser.parseProperty (http://localhost:9876/base/jspm_packages/npm/aurelia-validation@1.0.0-beta.1.0.1/implementation/validation-parser.js:38:33)
at …
=> Regex pattern does not match generated validation functions

doc/article/en-US/validation-basics.md
Casing was off and example did not work as-is.
=> Small typo in i18n ValidationMessageProvider usage example

doc/article/en-US/validation-basics.md
Official documentation shows examples with .parseMessage calls but that method has been renamed to .parse.
This replaces the obsolete calls with .parsein the documentation.
See also #454
=> Update obsolete .parseMessage calls in validation documentation

.vscode/settings.json, src/implementation/rule.ts, src/implementation/standard-validator.ts, src/implementation/validation-messages.ts, src/implementation/validation-rules.ts, src/property-accessor-parser.ts, src/util.ts, src/validate-result.ts, src/validation-controller.ts, test/property-accessor-parser.ts, test/validator.ts
Property keys are currently compared using strict equality. This should be loose equality since that's how they work natively too.
Example:
```
const obj1 = { 2: 'text' };
const obj2 = { '2': 'text' };
obj1[2] === obj1['2'] // true
obj2[2] === obj2['2'] // true
obj1[2] === obj2[2] // true
obj1['2'] === obj2['2'] // true
```
This PR fixes that. Closes #474
Also disabled `formatOnSave` and set the `tslint` sdk path in `.vscode/settings.json` because otherwise any contributer with other global settings will have to manually change this in the settings.json (or it's impossible to save any file with the correct formatting). And fixed a small linting error.
=> Fix number property accessors, small tslint fixes

src/aurelia-validation.ts, src/validate-binding-behavior.ts
@jdanyow Sorry I checked again and realized I forgot to name the binding behavior explicitly, it will break in production without it, because all class names will be mangled. There is a minor change in entry to ensure type definition works fine with static registration:
```js
import { configure as validationPlugin } from 'aurelia-validation'
export function configure(aurelia) {
aurelia.use.plugin(validationPlugin)
}
```
=> fix(BindingBehaviors): add explicit name

src/aurelia-validation.ts, src/config.ts, src/validation-controller-factory.ts, src/validation-controller.ts, test/validation-controller-factory.ts, test/validation-controller.ts
Fixes #535.
I moved `AureliaValidationConfiguration` to a separate file and added a method `defaultValidationTrigger` that users can call to globally configure the default validation trigger like so:
```ts
aurelia.use
.plugin("aurelia-validation", (config: AureliaValidationConfiguration) => {
config.defaultValidationTrigger(validateTrigger.manual);
});
```
I wasn't sure how to get the configured trigger into the `ValidationController` so I simply opted to register the config instance and inject it.
I considered making `AureliaValidationConfiguration.getDefaultValidationTrigger()` private to present a cleaner interface to users, but decided against it since this way the call in the `ValidationController` constructor can be type-checked.
=> feat(config): support global config option for default validation trigger

src/implementation/expression-visitor.ts
Fixes #537 
@jdanyow could you have a look and confirm that it's OK to keep the `AccessScope` imported from `aurelia-binding` and not redeclared as `any` ? See my detailed question here: https://github.com/aurelia/validation/issues/537#issuecomment-561052877
=> fix(ExpressionVisitor): not redeclare imports

src/property-accessor-parser.ts, test/property-accessor-parser.ts
https://github.com/aurelia/testing/issues/94#
=> Fix istanbul bug
